create:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_wheel_rot_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_rot_joint
    pid: {p: 0.1, i: 0.0, d: 0.0}
    
  right_wheel_rot_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_rot_joint
    pid: {p: 0.1, i: 0.0, d: 0.0}
